### ISSUE TITLE
Phonegap CLI

### ISSUE THREAD

**Issue by jurraburu** [Servoy/svyMobile#1]
Hi Tuan,

Great project! Thanks.

You mention that Phonegap CLI is needed (with NodeJs & GitScm). That is needed if you want to build locally on your PC right? If I use the web https://build.phonegap.com/ I do not need to install those, or are they allways required?

Regards,

Juan Urraburu

**Comment by tuanway** [comment]
Juan,

No. Those items are **not** required if you are building using their cloud based build tool.
