### ISSUE TITLE
Mobile Build Generator Issue

### ISSUE THREAD

**Issue by keeneyes** [Servoy/svyMobile#2]
When attempting to create a binary of any kind using the mobile build generator app (https://phonegaputils.servoy.com/), submitting an app via the Submit Build button fails to return anything.  The "Compilation will take a few minutes..." message displays continually, for hours if I let it go that long.  It doesn't seem to matter if I upload a keystore or certificate for Android or iOS, it behave the same.

I've tried this with Chrome and Safari on a Mac.  As a test, I've made sure the site is allowed to display pop ups in the browser in case it has something to do with that, but  that did not resolve the issue.

**Comment by tuanway** [comment]
Hi I believe the service was down yesterday.  It should be back up now.
